### ISSUE TITLE
Fail to build on linux

### ISSUE THREAD

**Issue by rzr** [Samsung/RT-OCF#9]
Hi,
I guess some files are not yet committed: 

ie: ./tools/internal/RT_OCF_error.py

```
bash -x ./tools/build_linux.sh
+ set -e
++ dirname ./tools/build_linux.sh
+ TOOLS_DIR=./tools
+ ./tools/build.py linux
Traceback (most recent call last):
  File "./tools/build.py", line 9, in <module>
    from internal.linux_adapter import LinuxAdapter
  File "(...)/RT-OCF/tools/internal/linux_adapter.py", line 19, in <module>
    from RT_OCF_error import RT_OCFError
ImportError: No module named RT_OCF_error
```

**Comment by chanijjani** [comment]
Hello, rzr.

I checked your comment and modified README.md.

To build at linux, you can just go to "RT-OCF/os/linux" and do "make" after saving "make menuconfig".

Sorry for very late answers. :)

**Comment by rzr** [comment]
Thanks for feedback, if it's fixed then you can close it, I reported just because of my curiosity, i am not using it yet.
